runtime: custom
env: flex
service: business-validation-service

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 4
  disk_size_gb: 10

env_variables:
  CLOUDSQL_CONNECTION_NAME: database
  CLOUDSQL_USER: postgres
  CLOUDSQL_PASSWORD: 'postgres'
